Corrigiendo problemas en validacion de get Products
Dium-dev/ATC_Back-end pull request #113
Opened 2023-08-16 19:45 UTC by EsteChar2906

Se cambio el type number de los campos 'limit' y 'page' por el type string en el dto de get products.
Esto debido a que en la query se toman como string.
En el archivo products.services se hace la conversión a numero entero para hacer la petición a la DB

2023-08-17 17:22 UTC, Fab1chapulino requested changes
Genial Carlos.

Checa el mensaje que pusiste en los decoradores _@IsString_; ponle que en lugar de decir 'número entero' diga 'string' para que no haya confusiones luego.

Fuera de eso todo bien

2023-08-17 20:37 UTC, EsteChar2906 commented
listo de una, ya lo cambio

2023-08-17 22:35 UTC, EsteChar2906 commented
Cambios aplicados

2023-08-18 14:46 UTC, Fab1chapulino approved these changes
Excelente

2023-08-19 17:04 UTC, lechugaxthz approved these changes

2023-08-19 17:04 UTC, merged