123 trabajar las primeras rutas del módulo resañas
Dium-dev/ATC_Back-end pull request #125
Opened 2023-08-23 16:25 UTC by Fab1chapulino

2023-08-24 17:44 UTC, lechugaxthz requested changes
No te olvides de ponerles su respectivos ’async await’ en los controladores. En lo cual corre pero no va a ser respetados en el deploy

Por otra parte. No se si está muy bien implementado el manejo de errores del create de reseña (en servicio) fijate que tienes un try catch dentro de otro. Y en cada uno mandas diferentes estatus y mensajes, además de que esa variable que pusiste psra guardar la reseña nunca va  a llegar a un caso de else en el if que tienes abajo en la línea 31, dado el caso de que no se haya creado tienes ya un catch por si pasa algo, que ese sería tu 'no se pudo crear la reseña' 

Lo mismo para las otras funciones. Fijate que una op try-catch es para todo lo interno, así que no necesitas hacer un try-catch dentro de otro, no se debería. Y en realidad si necesitas hacer varias funciones tienes que pensar que una función en el servicio tiene que llevar a cabo una operación, solo un objetivo. Ahí si, vos haces un try catch que dentro de ese llamas a otra función en otro con texto y esa función por su parte tiene un try catch.

2023-08-24 19:32 UTC, Fab1chapulino commented
Por cierto, agregué un cambio en la línea 81 del servicio de las direcciones, pues estaba rompiendo el servidor.

El error era que faltaba importar la interfaz que se estaba usando en esa linea de código, importación que viene incluida en este pull request.

2023-08-24 23:38 UTC, lechugaxthz approved these changes

2023-08-25 19:41 UTC, sofiavictoriafranco approved these changes

2023-08-25 21:44 UTC, merged