update product amount
Dium-dev/ATC_Back-end pull request #157
Opened 2023-09-14 17:13 UTC by CelesFlowers

2023-09-15 03:16 UTC, Fab1chapulino requested changes
Fino Celes. Tan solo habría que arreglar un par de conflictos.

Pero ¿Por qué haces que la nueva ruta reciba los datos (los id's y la nueva cantidad ) por params y no por body? 

Si los mandaras por body, bastaría con que hicieras las validaciones con un dto y además tendrías un codigo más limpio.

Otra cosa es que el método solo actualiza el _amount_ de un producto. Entonces, si se quisiera actualizar la cantidad de varios productos al mismo, ¿habría que hacerlo uno por uno?

2023-09-19 13:16 UTC, CelesFlowers commented
Fabi, cambie que pida los datos por body. Solo actualiza un producto, Carlos y Lechu opinaban que asi estaria bien. En mi opinion podria ser de ambas formas. Por favor lo conversas con Lechu y lo cambiamos si es necesario. Si podes aprobame esta pr asi queda esto al menos. 
Abrazo!

2023-09-19 15:40 UTC, Fab1chapulino approved these changes

2023-09-20 13:09 UTC, griimreaper approved these changes

2023-09-20 13:18 UTC, merged