Metodo get all user
Dium-dev/ATC_Back-end pull request #159
Opened 2023-09-15 16:56 UTC by griimreaper

2023-09-18 16:58 UTC, Fab1chapulino approved these changes

2023-09-19 01:07 UTC, Fab1chapulino requested changes
¿Por qué usas el _Math.floor_ para generar el _limitOFPages_? ¿No sería mejor el _Math.ceil_?
Además, podrías usar el método _.findAndCountAll_ para simplificar el código y no tener que consultar todos los datos de todos los usuarios a la DB.

2023-09-19 04:49 UTC, griimreaper commented
estas en lo cierto

2023-09-19 04:52 UTC, griimreaper reviewed
math.ceil

2023-09-19 22:00 UTC, Fab1chapulino reviewed
Piola

2023-09-19 22:01 UTC, Fab1chapulino approved these changes

2023-09-20 12:19 UTC, CelesFlowers approved these changes

2023-09-20 12:19 UTC, merged