154 crear método para actualizar una orden
Dium-dev/ATC_Back-end pull request #170
Opened 2023-09-27 15:16 UTC by antony2432

subiendo rama para el merge

2023-09-29 20:56 UTC, griimreaper approved these changes

2023-10-03 03:28 UTC, Fab1chapulino requested changes
Listo Anthony.

Solo que en algunas partes se repiten porciones de código. Tal y como pasa entre las líneas número 70 y 86:

```
        if (!orders)
        throw new InternalServerErrorException(
          'Algo salió mal al momento de buscar las órdenes. Revisar id enviado',
        );
      if (!orders.length)
        throw new NotFoundException(
          'No se encontraron órdenes asociadas a este usuario',
        );
      if (!orders)
        throw new InternalServerErrorException(
          'Algo salió mal al momento de buscar las órdenes. Revisar id enviado',
        );
      if (!orders.length)
        throw new NotFoundException(
          'No se encontraron órdenes asociadas a este usuario',
        );

```
Como ves se repiten un par de condicionales. Aunque también hay repeticiones entre las líneas número  142 y 155:

```
        order.state = updateDto.OrderStateEnum;
        order.save();
        return {
          statusCode: 200,
          message: 'Orden actualizada',
        };
      }

      order.state = updateDto.OrderStateEnum;
      order.save();
      return {
        statusCode: 200,
        message: 'Orden actualizada',
      };
```


De resto todo correcto, solo queda borrar unas cuantas líneas.

2023-10-18 04:45 UTC, antony2432 commented
Se han realizado correcciones en el código con respecto al manejo de errores y se han corregido las validaciones de class-validator en el DTO que se utiliza para actualizar el estado de una orden.

2023-10-23 17:31 UTC, Fab1chapulino approved these changes

2023-10-23 17:31 UTC, merged