179 payments tests
Dium-dev/ATC_Back-end pull request #183
Opened 2023-10-19 20:24 UTC by griimreaper

Testing para realizar pagos creado, 

valores nuevos agregados al .env:
HOST = http://localhost:3000 -> se debera cambiar luego por la url del servidor deployado

![image](https://github.com/Actualiza-Tu-Carro/back-end-atc/assets/121649026/ba5b0af3-211f-4267-b8eb-35e31e54fa6e)

ademas tuve que cambiar la manera de importar módulos para que el test no de errores de importacion.
 "src/payments..." -> "../payments..."

2023-10-20 14:08 UTC, CelesFlowers approved these changes

2023-10-20 14:09 UTC, CelesFlowers approved these changes

2023-10-20 18:15 UTC, Fab1chapulino reviewed
Bien hecho Leo. Muy bien testeado todo. Pero hay unas cuantas malas prácticas en cuanto al _mocking_ que se deben corregir.

1. Uso directo de las entidades para _mockear_. No tiene nada de malo, pero existen otros métodos con los que te pudiste ahorrar mucho trabajo. Por ejemplo, en lugar de hacer:
        ```const mockUser = new User(user);```

 Para luego hacer:

        ```const userFindByPkSpy = jest.spyOn(User, 'findByPk').mockResolvedValue(mockUser);```

Pudiste hacer un _mock_ de la entidad _User_ en el **array de _Providers_ del _TestingModule_** o utilizar la función de _automocking_ que nos provee Nest.js junto con la librería _createMock_. De esta forma, te ahorrarías el trabajo de crear instancias de las entidades en cada declaración _it_ y tan solo tendrías que "decirles" qué van a retornar mediante el uso de _faker_

2. Vi que aplicaste el patrón _triple A_ en la mayoría de los tests, pero encontré una incongruencia en una de las primeras declaraciones _it_; la que dice: **'should create a payment and return payment details'**. Verás:

```
      const mockPayment = new Payment(result.paymentId, order.total);
      jest.spyOn(Payment, 'create').mockResolvedValue(mockPayment);

      const mockResponse = {
        url: result.url,
        paymentId: result.paymentId,
      };
```

Debería de ir antes de (recuerda corregir el mocking de los modelos):

        `const result = await service.createPayment(order.total, mockUser.id, mockOrder.id);`


3. Noté que agregaste el módulo _DatabaseModule_ en los imports con tal de solucionar 'el error de reconocimiento de dependencias', por llamarlo de alguna forma. Sin embargo, esto crea una conexión real con la base de datos. La solución del error está relacionada con el registro de modelos mediante el _SequelizeModule.forFeature()_, pero sería muy complicado de explicar aquí así que te lo expondré por otro medio.

4. Estás haciendo peticiones a la API de mercado pago. Esto es una mala práctica puesto que no es necesario y además hará que tus _unit tests_ sean más lentos. Por lo que te recomiendo que leas la documentación sobre cómo _jest_ puede hacer _mocking_ de esta clase de módulos.

Eso sería todo, por acá te dejo unos enlaces con los cuales puedes guiarte al momento de hacer las correciones:

**Guía rápida de cómo testear una API Rest con Nestjs**
[https://www.tomray.dev/nestjs-unit-testing#unit-testing-pipes-in-nestjs](url)

**El objeto _jest_ y cómo hacer mocking de módulos**
[https://jestjs.io/docs/jest-object#jestmockmodulename-factory-options](url)

**Y otra lectura que recomiendo a cerca del funcionamiento de los _providers**_
[https://docs.nestjs.com/providers#custom-providers](url)

2023-10-20 18:16 UTC, Fab1chapulino requested changes
Bien hecho Leo. Muy bien testeado todo. Pero hay unas cuantas malas prácticas en cuanto al _mocking_ que se deben corregir.

1. Uso directo de las entidades para _mockear_. No tiene nada de malo, pero existen otros métodos con los que te pudiste ahorrar mucho trabajo. Por ejemplo, en lugar de hacer:
        ```const mockUser = new User(user);```

 Para luego hacer:

        ```const userFindByPkSpy = jest.spyOn(User, 'findByPk').mockResolvedValue(mockUser);```

Pudiste hacer un _mock_ de la entidad _User_ en el **array de _Providers_ del _TestingModule_** o utilizar la función de _automocking_ que nos provee Nest.js junto con la librería _createMock_. De esta forma, te ahorrarías el trabajo de crear instancias de las entidades en cada declaración _it_ y tan solo tendrías que "decirles" qué van a retornar mediante el uso de _faker_

2. Vi que aplicaste el patrón _triple A_ en la mayoría de los tests, pero encontré una incongruencia en una de las primeras declaraciones _it_; la que dice: **'should create a payment and return payment details'**. Verás:

```
      const mockPayment = new Payment(result.paymentId, order.total);
      jest.spyOn(Payment, 'create').mockResolvedValue(mockPayment);

      const mockResponse = {
        url: result.url,
        paymentId: result.paymentId,
      };
```

Debería de ir antes de (recuerda corregir el mocking de los modelos):

        `const result = await service.createPayment(order.total, mockUser.id, mockOrder.id);`


3. Noté que agregaste el módulo _DatabaseModule_ en los imports con tal de solucionar 'el error de reconocimiento de dependencias', por llamarlo de alguna forma. Sin embargo, esto crea una conexión real con la base de datos. La solución del error está relacionada con el registro de modelos mediante el _SequelizeModule.forFeature()_, pero sería muy complicado de explicar aquí así que te lo expondré por otro medio.

4. Estás haciendo peticiones a la API de mercado pago. Esto es una mala práctica puesto que no es necesario y además hará que tus _unit tests_ sean más lentos. Por lo que te recomiendo que leas la documentación sobre cómo _jest_ puede hacer _mocking_ de esta clase de módulos.

Eso sería todo, por acá te dejo unos enlaces con los cuales puedes guiarte al momento de hacer las correciones:

**Guía rápida de cómo testear una API Rest con Nestjs**
[https://www.tomray.dev/nestjs-unit-testing#unit-testing-pipes-in-nestjs](url)

**El objeto _jest_ y cómo hacer mocking de módulos**
[https://jestjs.io/docs/jest-object#jestmockmodulename-factory-options](url)

**Y otra lectura que recomiendo a cerca del funcionamiento de los _providers**_
[https://docs.nestjs.com/providers#custom-providers](url)

2023-10-21 05:00 UTC, griimreaper commented
Genial Fabi he corregido el punto 1, 2 y 4 luego me dices como implementar una base de datos ficticia para los tests. 
Gracias por tu devolución.

2023-10-23 23:40 UTC, Fab1chapulino approved these changes
Piola Leo, todo está perfecto.
No te preocupes por ahora por el error que habíamos tenido antes, pues se puede corregir y ver a profundidad la solución en futuras ramas

2023-10-24 20:01 UTC, merged