complete el update-direction.dto
Dium-dev/ATC_Back-end pull request #48
Opened 2023-08-08 17:18 UTC by sofiavictoriafranco

validacion de tipos de datos en update direction

2023-08-08 18:21 UTC, lechugaxthz requested changes
Al igual que en `UpdateUser.dto`
aplicar los decoradores de la librería `class-validator`

```ts
@IsOptional()
@IsNumber()
@IsString()
```
a los unicos que debes pasarle un parametro es a `@IsNumber()` e `@IsString()`
siendo este `{message: 'tu mensaje de error'}`
siendo ejemplos:
`el codigo postal deben ser solo numeros !`
`la ciudad no puede ser un numero`

de igual modo, seguro realicemos cambios posteriormente para validar de que la ciudad coincida con el estado... pero va para mas adelante !

2023-08-09 14:26 UTC, martinalturria approved these changes
Me parece que quedo bien el Dto.

2023-08-09 15:26 UTC, EsteChar2906 approved these changes

2023-08-09 15:28 UTC, lechugaxthz approved these changes

2023-08-09 15:28 UTC, merged