validacion de datos para crear direccion
Dium-dev/ATC_Back-end pull request #68
Opened 2023-08-09 20:15 UTC by sofiavictoriafranco

create direction dto

2023-08-09 20:19 UTC, EsteChar2906 commented
genial, yo tengo una duda, no necesitaríamos el id del user, para relacionarlo al crear la dirección o recibiríamos el Id aparte.

2023-08-09 20:48 UTC, lechugaxthz requested changes
Agregar 
```ts
@IsNotEmpty({message: <con su mensaje correspondiente diciendo el campo x no debe estar vacío>}) 
```

2023-08-10 18:43 UTC, EsteChar2906 approved these changes

2023-08-10 18:56 UTC, lechugaxthz approved these changes

2023-08-10 18:56 UTC, merged