Cambio de contraseña y actualizacion
Dium-dev/ATC_Back-end pull request #81
Opened 2023-08-11 16:27 UTC by EsteChar2906

Avance de la implementación para que el usuario recupere y cambie la contraseña. 
Falta implementar la lógica del token y el envío de correo, lo cual, estaré indicando la otra semana. En nuevas tareas.
Estas rutas ya están documentadas.
Cuando finalice indicare las rutas de cada funcionalidad.

Quedo atento a comentarios.

2023-08-11 16:41 UTC, lechugaxthz requested changes
faltaron `async await` . fijate el `auth.controller.ts`
 y para despues de que sigas con lo otro, recuerda cambiar el `reset-password.dto` porque no tendras la `resetPasswordToken`!

2023-08-11 21:29 UTC, EsteChar2906 commented
Cambios aplicados

2023-08-11 21:54 UTC, lechugaxthz approved these changes

2023-08-12 18:19 UTC, lechugaxthz approved these changes

2023-08-13 04:47 UTC, merged