documentación y manejo de errores de eliminar dirección
Dium-dev/ATC_Back-end pull request #85
Opened 2023-08-11 18:12 UTC by sofiavictoriafranco

2023-08-11 19:55 UTC, lechugaxthz requested changes
Fijate que no coinciden los mensajes de error entre `documentacion` (controller) y `manejo de error` (service)

2023-08-11 21:56 UTC, lechugaxthz approved these changes
bien, ya para mas adelante aplicar el `@HttpCode(<tu valor de status>)` para poder personalizar los `status code` que devolvemos tras la petición

2023-08-11 22:40 UTC, EsteChar2906 requested changes
en el archivo directions.service importas desde @nestjs/common en la linea 1 y 5

2023-08-11 22:56 UTC, lechugaxthz approved these changes

2023-08-12 18:23 UTC, lechugaxthz approved these changes

2023-08-13 15:31 UTC, Fab1chapulino approved these changes
Parece estar todo bien, solo que en futuros commits hay que corregir los nombres de algunas dependencias, como en directions.controllers.ts o directions.service.ts, donde sus respectivas clases tienen 'Direetions...' en lugar de 'Directions...'. Lo mismo pasa con los Dto's, a excepción de eso todo está bien.

2023-08-13 17:57 UTC, EsteChar2906 approved these changes

2023-08-13 17:57 UTC, merged