interfaz de dirección
Dium-dev/ATC_Back-end pull request #87
Opened 2023-08-11 19:22 UTC by sofiavictoriafranco

2023-08-11 20:00 UTC, lechugaxthz requested changes
Falta `async await` dentro del controller `update`.
y otra cosa, sería necesario mandar nuevamente la dirección una vez guardada ? o seria mejor mandar un mensaje de confirmación ? 

más allá de eso, la interfaz está bien implementada !

2023-08-11 21:59 UTC, sofiavictoriafranco commented
Me parece mejor mandar la dirección para ver los cambios que se realizaron

2023-08-12 18:26 UTC, lechugaxthz approved these changes

2023-08-13 15:23 UTC, Fab1chapulino approved these changes
Todo correcto Sofi.

2023-08-13 15:52 UTC, merged